### ISSUE TITLE
The installer doesn't boot

### ISSUE THREAD

**Issue by cristian907** [MSCLoaderPro/MSCModLoaderPro#13]
When I try to use the .exe nothing happens
Windows 10

**Comment by Athlon007** [comment]
Could you please contact me on Discord? Athlon#3670

**Comment by Athlon007** [comment]
I updated the Installer, could you try starting it?

**Comment by gabrielpauletti** [comment]
oi, estou com um problema na tela de loading, meu jogo abre, eu ouço os passaros e consigo até caminhar, mas não vejo nada, fica na tela ¨loading mods in 1995¨e não sai

**Comment by Athlon007** [comment]
> oi, estou com um problema na tela de loading, meu jogo abre, eu ouço os passaros e consigo até caminhar, mas não vejo nada, fica na tela ¨loading mods in 1995¨e não sai

Se você estiver usando MOP, atualize-o. https://www.nexusmods.com/mysummercar/mods/146

**Comment by Athlon007** [comment]
No new updates have been provided to the topic, so it's considered as solved.

Closed.
