### ISSUE TITLE
Console keybind doesn't change

### ISSUE THREAD

**Issue by Lanxtot** [MSCLoaderPro/MSCModLoaderPro#14]
I want to assign the backquote key to another function without the console opening up every time. If I press on 'backquote' it changes to 'press key(s)' but no matter what I press, it still says press key.
In this video https://youtu.be/8CrHaqFnbso I press many keys on my keyboard, then I press backquote and you can see that it still works as the console key.

**Comment by Fredrik95** [comment]
Okay, I think I know what's wrong, will be fixed in the next update hopefully!

**Comment by Fredrik95** [comment]
Fixed it, will be in the next update.

Thank you for the report!
