### ISSUE TITLE
satsuman part bug

### ISSUE THREAD

**Issue by tonzza95** [MSCLoaderPro/MSCModLoaderPro#15]
the satsuma parts do not stick but come loose after tightening and the tractor trailer teleports to the backyard
the satsuma is completely assembled when i visit the teimo and come back home so the parts are loose

**Comment by tonzza95** [comment]
when i was dead then a newspaper appeared and at the same time i heard the parts of satsuma come off

**Comment by Athlon007** [comment]
This is not Mod Loader Pro bug, but likely MOP bug. Closing.

**Comment by tonzza95** [comment]
can you fixed it
