### ISSUE TITLE
[BUG]mod loader flashes

### ISSUE THREAD

**Issue by LA3519** [MSCLoaderPro/MSCModLoaderPro#17]
When i load the game everything looks fie but when i press the mods button it flashes nonstop i cant get a vid since my pc is crap but i cant navigate through it

**Comment by LA3519** [comment]
UPDATE: it wasss getting late so i put my pc in sleep mode and then when i load up the game for a minute the bug was gone idk what happend but this is solved i guess just put your pc in sleep for a few then try it again

**Comment by Athlon007** [comment]
What do you mean it is flashing?

**Comment by LA3519** [comment]
> What do you mean it is flashing?

when i open the menu it just flashes super fast and then it happend again no way to fix it and thats not the worst when i opend my keybinda the g27 controls and stickshift controls were just randomly doingg stuff while i didn't press anything

**Comment by LA3519** [comment]
This is solved now
apparently when i plug my steering wheel in before i launch the game it makes conflict or something so it wasn't bugged
:P
