### ISSUE TITLE
Most mods have an error and ingame mod settings of the concerned mods do not show up.

### ISSUE THREAD

**Issue by Parking955** [MSCLoaderPro/MSCModLoaderPro#21]
**Describe the bug**
At startup, this error appears:
ERROR: (mod)! Details: 
Object reference not set to an
instance of an object in void
onload( ).
the mod settings of those mods do not show up.

**To Reproduce**
The error manifests itself at startup and is only visible from the console.

**Expected behavior**
the expected behavior is that the mods would work

**Screenshots**

**output_log.txt**
[output_log.txt](https://github.com/MSCLoaderPro/MSCModLoaderPro/files/6642711/output_log.txt)
![20210612202603_1](https://user-images.githubusercontent.com/85803906/121785864-9cce7b80-cbbc-11eb-8038-2f35e9b7d6be.jpg)

**Additional context**

**Comment by Athlon007** [comment]
This is really weird, I have much of those mods and they work just fine...

Please try reinstalling Mod Loader Pro by downloading the Installer again. https://mscloaderpro.github.io/

**Comment by Parking955** [comment]
I just checked in the modsettings for a mod that I know has settings (noclip, keybind) and this is what I found:

{
  "settings": [],
  "isDisabled": false
}
There should be something in between the brackets after settings.

On the pickup for example, there are force feedback settings in the "settings" part.

I tried reinstalling MLP but that did nothing.

**Comment by Parking955** [comment]
Hi, I fixed the issue by deleting the settings folder in the mods folder.
Thanks a lot for your help

**Comment by Athlon007** [comment]
I guess it can be closed then.
