### ISSUE TITLE
Red Error Messages in Command. (And FifthGear mod not working.)

### ISSUE THREAD

**Issue by Satsumarider** [MSCLoaderPro/MSCModLoaderPro#3]
Hello mod creator(s)! I've been seeing these red error messages in the Commands, one small one (as seen in the photo on NexusMods Posts section, Assuming I didn't report the bug improperly and it didn't get deleted, if so sorry in advance.) and one that is big, the big one says: 'System.IO.IsolatedStorage.IsolatedStorageExeption...'

The FifthGear mod also doesn't work as of right now and also makes a red error message of it's own. (So three error messages in total.)

Here is the Pastebin for the output_log.txt :

https://pastebin.com/0A8zRmdd

And if I somehow failed to make that Pastebin properly, here is the Google Drive for it:

https://drive.google.com/file/d/1b0UMaE158BZUx3oJBjF4F4Npa0MXGBKe/view?usp=sharing

Thank you everyone who made this ground-breaking modloader. :D

**Comment by Athlon007** [comment]
This is a problem of Athlon's Tweaks Pack (well, my tweaks pack). Fortunately, I released an update fixing that issue :)

[You can grab it here](https://www.nexusmods.com/mysummercar/mods/163)

**Comment by Athlon007** [comment]
I just noticed that the second bug is related to ProLoader indeed.

It will be fixed in the next update.

**Comment by Athlon007** [comment]
Another thing I noticed, seems like Nexus log in failed. Please log out and log back in again.

**Comment by Athlon007** [comment]
Fixed in 1.0.6.
