### ISSUE TITLE
Cursor doesn t appear in game menu ( esc) [BUG]

### ISSUE THREAD

**Issue by Mejmenojenikdo** [MSCLoaderPro/MSCModLoaderPro#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**output_log.txt**
Please provide the "output_log.txt" file form My Summer Car folder.

**Additional context**

**Comment by Tresquel** [comment]
first please fill out the template
second you might be able to fix it by opening grab anything's menu, so just do ctrl + p to open the menu and close it and the problem should go away

**Comment by Fredrik95** [comment]
There's a lot of things that could interfere with that, the mod loader itself doesn't touch the cursor behaviour at all, so it's likely some mod that is involved and not the loader.
