### ISSUE TITLE
[BUG] Pause menu doesn't work.

### ISSUE THREAD

**Issue by Snowymirror** [MSCLoaderPro/MSCModLoaderPro#34]
Unable to close my pause menu when hitting ESC (Escape)
I open the escape menu to close the map mod that I have open.

**Comment by Tresquel** [comment]
this isn't a bug with the mod loader itself but with your map mod

**Comment by Fredrik95** [comment]
This isn't a bug at all, mods or not. You can't close the "pause menu" with ESC in any version of the game. For whatever reason the developer of the game chose F1 as the button to close and/or pressing "Resume".
