### ISSUE TITLE
 I have a problem with msc loader

### ISSUE THREAD

**Issue by michal812** [MSCLoaderPro/MSCModLoaderPro#38]
after enabling my save in the console (in the lower right corner) I get this message
(MSCLoader detected. Mscloader 1.1.5 is supported. If mscloader has been updated, contact the mod author.
Error: Wrong version of) I guess I need version 1.1.5 and there is no 1.1.1 please help.

This is a screenshot from this consol
![This is a screenshot from this console](https://user-images.githubusercontent.com/92880358/138139460-4cea2224-ae6f-4da7-a7ee-84451eb31f2c.png)

**Comment by michal812** [comment]
Fredrik95-help?

**Comment by Tresquel** [comment]
Could you send us the log?
