### ISSUE TITLE
UI Size on Triple Screen Resolution

### ISSUE THREAD

**Issue by Werner345** [MSCLoaderPro/MSCModLoaderPro#4]
Hello, so if i play on 7680x1440 Resolution with my 3 Screens, it seems like the UI of the Mods orientate there size on the width of the screen. Like you can see in the picture, it makes parts of the Windows like the Mods menu not visible und not usable. This Problem also appeared with the other ModLoader. This problem was fixed with a Slider to scale the size of the Mods UI. It also looks like this with Mods like the Backpack Mod, when i open my Inventory Window.
![Unbenannt](https://user-images.githubusercontent.com/83514880/116792890-c37c9b00-aac3-11eb-90ff-d9cd93f794af.PNG)

If it helps i also list my installed Mods:
![Unbenannt1](https://user-images.githubusercontent.com/83514880/116792947-122a3500-aac4-11eb-88f7-ecd328de23e6.PNG)

Thanks for hearing me out and wish you all a nice day :)

**Comment by Fredrik95** [comment]
Hi, thanks for the report. I think I've solved the issue (was not easy to test with a 1080p monitor :D ), will be in the next update. It should be automatic now, no slider required. I'll leave this issue open for now and you can test it out yourself when the update drops.

**Comment by Fredrik95** [comment]
A fix for the UI in ultrawide resolutions are in the 1.0.6 update.

Thanks for bringing this to our attention!

**Comment by Werner345** [comment]
Awesome, it works great. Thanks so much :)

Ony the Inventory Window from the Mod "AdvancedBackpack" still has this problem, but i guess this has to be fixed by the Mod Autor from this Mod.

**Comment by Fredrik95** [comment]
Great to hear it!

Yeah, unfortunately we can't do much about the specific functionality of the mods, but I'm sure if you post a bug report detailing the problem they'll handle it. :)

Have a continued nice day!

Closing the issue.
